name: Sync Logseq Journals to Notion Mirror

on:
  workflow_dispatch:

jobs:
  sync-logseq-journals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Python script
        env:
          NOTION_API_KEY: ${{secrets.NOTION_API_KEY}} 
          NOTION_LOGSEQ_MIRROR_DATABASE_URL: ${{secrets.NOTION_LOGSEQ_MIRROR_DATABASE_URL}}
        run: |
          python scripts/sync_logseq_journals.py
