name: Sync Logseq Journals to Notion Mirror

on:
  workflow_dispatch:

jobs:
  sync-logseq-journals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
